<a href="https://colab.research.google.com/github/Verdexte12/AluraStoreLatam/blob/main/Leyendo_distintos_tipos_de_archivos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Leyendo distintos tipos de archivos**

In [179]:
import pandas as pd

##**1- CSV**

In [180]:
datos= pd.read_csv("superstore_data.csv")
datos.head()

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [181]:
datos= pd.read_csv("superstore_data_punto_coma.csv", sep=";")
datos.head()

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [182]:
datos_seleccion= datos[["Id","Year_Birth","Income"]]
datos_seleccion.head()

      Id  Year_Birth   Income
0   1826        1970  84835.0
1      1        1961  57091.0
2  10476        1958  67267.0
3   1386        1967  32474.0
4   5371        1989  21474.0

In [183]:
datos_seleccion= pd.read_csv("superstore_data_punto_coma.csv", sep=";", usecols=[0,1,4])
datos_seleccion.head()

      Id  Year_Birth   Income
0   1826        1970  84835.0
1      1        1961  57091.0
2  10476        1958  67267.0
3   1386        1967  32474.0
4   5371        1989  21474.0

In [184]:
datos_seleccion.to_csv("datos_seleccion.csv")

In [185]:
clientes_seleccion= pd.read_csv("/content/datos_seleccion.csv")
clientes_seleccion.head()

   Unnamed: 0     Id  Year_Birth   Income
0           0   1826        1970  84835.0
1           1      1        1961  57091.0
2           2  10476        1958  67267.0
3           3   1386        1967  32474.0
4           4   5371        1989  21474.0

In [186]:
datos_seleccion.to_csv("datos_seleccion.csv", index=False)

In [187]:
clientes_seleccion= pd.read_csv("/content/datos_seleccion.csv")
clientes_seleccion.head()

      Id  Year_Birth   Income
0   1826        1970  84835.0
1      1        1961  57091.0
2  10476        1958  67267.0
3   1386        1967  32474.0
4   5371        1989  21474.0

##**2- Excel**

In [188]:
datos= pd.read_excel("emisiones_carbono_mundo.xlsx")
datos

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),1.917451e+08,1.676816e+08,9.595774e+07,8.472111e+06,7.554583e+07,6.846796e+07,...,2.965062e+07,2.592953e+08,1.856237e+07,1.462356e+08,1.728967e+08,1.497893e+08,1.316946e+08,1.632953e+06,1.598244e+08,1.598244e+08
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),5.536620e+08,5.445386e+08,5.435572e+08,7.089842e+07,8.368044e+08,9.121415e+08,...,9.855223e+08,9.506959e+08,1.036294e+09,1.099779e+09,1.135044e+08,1.031811e+09,8.133007e+07,7.776749e+08,7.921371e+08,7.921371e+08
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542e+09,1.242810e+08,6.836998e+08,6.383070e+08,6.453552e+08,6.054363e+08,...,1.669423e+08,1.503240e+08,1.533630e+09,1.668337e+09,1.603775e+08,1.557664e+09,1.788786e+09,1.782739e+09,1.692248e+08,1.692248e+08
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832e+09,7.235379e+08,6.963079e+07,6.724178e+09,6.541579e+09,6.733479e+09,...,5.850886e+09,5.944654e+09,5.942800e+09,5.807128e+09,6.026182e+09,6.080600e+09,6.104134e+09,6.362975e+09,6.481217e+09,6.481217e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Samoa,WSM,East Asia & Pacific,CO2 emissions (metric tons per capita),5.528357e+07,6.097561e+08,6.042661e+08,6.582215e+08,5.928069e+08,7.056748e+08,...,1.066843e+09,1.057703e+09,1.048702e+09,1.092498e+09,1.240246e+09,1.542099e+09,1.586830e+09,1.478626e+09,1.522124e+09,1.522124e+09
211,"Yemen, Rep.",YEM,Middle East & North Africa,CO2 emissions (metric tons per capita),5.670374e+07,6.909374e+08,7.047931e+08,6.271049e+08,6.532557e+08,7.060805e+08,...,9.639785e+08,8.584910e+08,1.106688e+09,1.062211e+09,5.113617e+08,3.993638e+08,3.596216e+08,3.410684e+08,3.806334e+08,3.806334e+08
212,South Africa,ZAF,Sub-Saharan Africa,CO2 emissions (metric tons per capita),6.729799e+09,6.424622e+09,6.175430e+09,6.219194e+09,6.215847e+09,6.378790e+09,...,7.869816e+09,8.077958e+09,8.138264e+09,8.212241e+09,7.669938e+09,7.563739e+09,7.641675e+09,7.515679e+09,7.507736e+09,7.507736e+09
213,Zambia,ZMB,Sub-Saharan Africa,CO2 emissions (metric tons per capita),3.409296e+08,3.492322e+08,3.372244e+07,2.899561e+08,2.412696e+08,2.341532e+08,...,2.174967e+08,2.786007e+07,2.840576e+08,3.045496e+08,3.123550e+08,3.251148e+08,4.040678e+08,4.454891e+08,3.807171e+08,3.807171e+08
214,Zimbabwe,ZWE,Sub-Saharan Africa,CO2 emissions (metric tons per capita),1.585444e+09,1.713321e+09,1.694416e+09,1.539741e+09,1.417186e+09,1.356619e+08,...,8.848855e+07,9.157349e+08,9.198241e+08,8.891041e+08,8.997700e+08,7.854408e+07,7.262971e+08,8.574113e+08,8.029785e+07,8.029785e+07

In [189]:
pd.ExcelFile("emisiones_carbono_mundo.xlsx").sheet_names

['CO2_emission']

In [190]:
intervalos= pd.read_excel("emisiones_carbono_mundo.xlsx", usecols="A:D")
intervalos

,Country Name,country_code,Region,Indicator Name
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita)
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita)
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita)
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita)
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita)
...,...,...,...,...
210,Samoa,WSM,East Asia & Pacific,CO2 emissions (metric tons per capita)
211,"Yemen, Rep.",YEM,Middle East & North Africa,CO2 emissions (metric tons per capita)
212,South Africa,ZAF,Sub-Saharan Africa,CO2 emissions (metric tons per capita)
213,Zambia,ZMB,Sub-Saharan Africa,CO2 emissions (metric tons per capita)
214,Zimbabwe,ZWE,Sub-Saharan Africa,CO2 emissions (metric tons per capita)

In [191]:
intervalos= pd.read_excel("emisiones_carbono_mundo.xlsx", usecols="A:D", nrows=10)
intervalos

,Country Name,country_code,Region,Indicator Name
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita)
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita)
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita)
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita)
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita)
5,United Arab Emirates,ARE,Middle East & North Africa,CO2 emissions (metric tons per capita)
6,Argentina,ARG,Latin America & Caribbean,CO2 emissions (metric tons per capita)
7,Armenia,ARM,Europe & Central Asia,CO2 emissions (metric tons per capita)
8,American Samoa,ASM,East Asia & Pacific,CO2 emissions (metric tons per capita)
9,Antigua and Barbuda,ATG,Latin America & Caribbean,CO2 emissions (metric tons per capita)

In [192]:
intervalos.to_excel("intervalos.xlsx", index=False)

In [193]:
sheet_id= "1dcgAf7izZux17JJiA2K8xiLfBDXLcqw3D3X6ITRjC_4"
url= f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet"

In [194]:
datos_co2_sheets= pd.read_csv(url)
datos_co2_sheets

,País,ISO 3166-1 alpha-3,Año,Total,Carbón,Aceite,Gas,Cemento,Quema,Otros,Per Capita
0,Afganistán,AFG,1750,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afganistán,AFG,1751,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afganistán,AFG,1752,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afganistán,AFG,1753,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afganistán,AFG,1754,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,3.609674e+10,1.450697e+10,1.224263e+10,7.144928e+09,1.507923e+09,391992176.0,302294047.0,4749682.0
63100,Global,WLD,2018,3.682651e+10,1.474683e+10,1.226602e+10,7.529847e+09,1.569218e+09,412115746.0,302478706.0,4792753.0
63101,Global,WLD,2019,3.708256e+10,1.472598e+10,1.234565e+10,7.647528e+09,1.617507e+09,439253991.0,306638573.0,4775633.0
63102,Global,WLD,2020,3.526409e+10,1.417456e+10,1.119181e+10,7.556290e+09,1.637538e+09,407583673.0,296301685.0,4497423.0
63103,Global,WLD,2021,3.712385e+10,1.497960e+10,1.183716e+10,7.921829e+09,1.672592e+09,416525563.0,296145746.0,4693699.0

##**3- Json**

In [195]:
import requests
import json

In [196]:
datos_frutas = requests.get('https://fruityvice.com/api/fruit/all')
datos_frutas

In [197]:
resultado = json.loads(datos_frutas.text)
resultado

[{'name': 'Persimmon',
  'id': 52,
  'family': 'Ebenaceae',
  'order': 'Rosales',
  'genus': 'Diospyros',
  'nutritions': {'calories': 81,
   'fat': 0.0,
   'sugar': 18.0,
   'carbohydrates': 18.0,
   'protein': 0.0}},
 {'name': 'Strawberry',
  'id': 3,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Fragaria',
  'nutritions': {'calories': 29,
   'fat': 0.4,
   'sugar': 5.4,
   'carbohydrates': 5.5,
   'protein': 0.8}},
 {'name': 'Banana',
  'id': 1,
  'family': 'Musaceae',
  'order': 'Zingiberales',
  'genus': 'Musa',
  'nutritions': {'calories': 96,
   'fat': 0.2,
   'sugar': 17.2,
   'carbohydrates': 22.0,
   'protein': 1.0}},
 {'name': 'Tomato',
  'id': 5,
  'family': 'Solanaceae',
  'order': 'Solanales',
  'genus': 'Solanum',
  'nutritions': {'calories': 74,
   'fat': 0.2,
   'sugar': 2.6,
   'carbohydrates': 3.9,
   'protein': 0.9}},
 {'name': 'Pear',
  'id': 4,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Pyrus',
  'nutritions': {'calories': 57,
   'fat': 0.1,
   'sugar': 10.0,
   'carbohydrates': 15.0,
   'protein': 0.4}},
 {'name': 'Durian',
  'id': 60,
  'family': 'Malvaceae',
  'order': 'Malvales',
  'genus': 'Durio',
  'nutritions': {'calories': 147,
   'fat': 5.3,
   'sugar': 6.75,
   'carbohydrates': 27.1,
   'protein': 1.5}},
 {'name': 'Blackberry',
  'id': 64,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Rubus',
  'nutritions': {'calories': 40,
   'fat': 0.4,
   'sugar': 4.5,
   'carbohydrates': 9.0,
   'protein': 1.3}},
 {'name': 'Lingonberry',
  'id': 65,
  'family': 'Ericaceae',
  'order': 'Ericales',
  'genus': 'Vaccinium',
  'nutritions': {'calories': 50,
   'fat': 0.34,
   'sugar': 5.74,
   'carbohydrates': 11.3,
   'protein': 0.75}},
 {'name': 'Kiwi',
  'id': 66,
  'family': 'Actinidiaceae',
  'order': 'Struthioniformes',
  'genus': 'Apteryx',
  'nutritions': {'calories': 61,
   'fat': 0.5,
   'sugar': 9.0,
   'carbohydrates': 15.0,
   'protein': 1.1}},
 {'name': 'Lychee',
  'id': 67,
  'family': 'Sapindaceae',
  'order': 'Sapindales',
  'genus': 'Litchi',
  'nutritions': {'calories': 66,
   'fat': 0.44,
   'sugar': 15.0,
   'carbohydrates': 17.0,
   'protein': 0.8}},
 {'name': 'Pineapple',
  'id': 10,
  'family': 'Bromeliaceae',
  'order': 'Poales',
  'genus': 'Ananas',
  'nutritions': {'calories': 50,
   'fat': 0.12,
   'sugar': 9.85,
   'carbohydrates': 13.12,
   'protein': 0.54}},
 {'name': 'Fig',
  'id': 68,
  'family': 'Moraceae',
  'order': 'Rosales',
  'genus': 'Ficus',
  'nutritions': {'calories': 74,
   'fat': 0.3,
   'sugar': 16.0,
   'carbohydrates': 19.0,
   'protein': 0.8}},
 {'name': 'Gooseberry',
  'id': 69,
  'family': 'Grossulariaceae',
  'order': 'Saxifragales',
  'genus': 'Ribes',
  'nutritions': {'calories': 44,
   'fat': 0.6,
   'sugar': 0.0,
   'carbohydrates': 10.0,
   'protein': 0.9}},
 {'name': 'Passionfruit',
  'id': 70,
  'family': 'Passifloraceae',
  'order': 'Malpighiales',
  'genus': 'Passiflora',
  'nutritions': {'calories': 97,
   'fat': 0.7,
   'sugar': 11.2,
   'carbohydrates': 22.4,
   'protein': 2.2}},
 {'name': 'Plum',
  'id': 71,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 46,
   'fat': 0.28,
   'sugar': 9.92,
   'carbohydrates': 11.4,
   'protein': 0.7}},
 {'name': 'Orange',
  'id': 2,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 43,
   'fat': 0.2,
   'sugar': 8.2,
   'carbohydrates': 8.3,
   'protein': 1.0}},
 {'name': 'GreenApple',
  'id': 72,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Malus',
  'nutritions': {'calories': 21,
   'fat': 0.1,
   'sugar': 6.4,
   'carbohydrates': 3.1,
   'protein': 0.4}},
 {'name': 'Raspberry',
  'id': 23,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Rubus',
  'nutritions': {'calories': 53,
   'fat': 0.7,
   'sugar': 4.4,
   'carbohydrates': 12.0,
   'protein': 1.2}},
 {'name': 'Watermelon',
  'id': 25,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'genus': 'Citrullus',
  'nutritions': {'calories': 30,
   'fat': 0.2,
   'sugar': 6.0,
   'carbohydrates': 8.0,
   'protein': 0.6}},
 {'name': 'Lemon',
  'id': 26,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 29,
   'fat': 0.3,
   'sugar': 2.5,
   'carbohydrates': 9.0,
   'protein': 1.1}},
 {'name': 'Mango',
  'id': 27,
  'family': 'Anacardiaceae',
  'order': 'Sapindales',
  'genus': 'Mangifera',
  'nutritions': {'calories': 60,
   'fat': 0.38,
   'sugar': 13.7,
   'carbohydrates': 15.0,
   'protein': 0.82}},
 {'name': 'Blueberry',
  'id': 33,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Fragaria',
  'nutritions': {'calories': 29,
   'fat': 0.4,
   'sugar': 5.4,
   'carbohydrates': 5.5,
   'protein': 0.0}},
 {'name': 'Apple',
  'id': 6,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Malus',
  'nutritions': {'calories': 52,
   'fat': 0.4,
   'sugar': 10.3,
   'carbohydrates': 11.4,
   'protein': 0.3}},
 {'name': 'Guava',
  'id': 37,
  'family': 'Myrtaceae',
  'order': 'Myrtales',
  'genus': 'Psidium',
  'nutritions': {'calories': 68,
   'fat': 1.0,
   'sugar': 9.0,
   'carbohydrates': 14.0,
   'protein': 2.6}},
 {'name': 'Apricot',
  'id': 35,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 15,
   'fat': 0.1,
   'sugar': 3.2,
   'carbohydrates': 3.9,
   'protein': 0.5}},
 {'name': 'Melon',
  'id': 41,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitaceae',
  'genus': 'Cucumis',
  'nutritions': {'calories': 34,
   'fat': 0.0,
   'sugar': 8.0,
   'carbohydrates': 8.0,
   'protein': 0.0}},
 {'name': 'Tangerine',
  'id': 77,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 45,
   'fat': 0.4,
   'sugar': 9.1,
   'carbohydrates': 8.3,
   'protein': 0.0}},
 {'name': 'Pitahaya',
  'id': 78,
  'family': 'Cactaceae',
  'order': 'Caryophyllales',
  'genus': 'Cactaceae',
  'nutritions': {'calories': 36,
   'fat': 0.4,
   'sugar': 3.0,
   'carbohydrates': 7.0,
   'protein': 1.0}},
 {'name': 'Lime',
  'id': 44,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 25,
   'fat': 0.1,
   'sugar': 1.7,
   'carbohydrates': 8.4,
   'protein': 0.3}},
 {'name': 'Pomegranate',
  'id': 79,
  'family': 'Lythraceae',
  'order': 'Myrtales',
  'genus': 'Punica',
  'nutritions': {'calories': 83,
   'fat': 1.2,
   'sugar': 13.7,
   'carbohydrates': 18.7,
   'protein': 1.7}},
 {'name': 'Dragonfruit',
  'id': 80,
  'family': 'Cactaceae',
  'order': 'Caryophyllales',
  'genus': 'Selenicereus',
  'nutritions': {'calories': 60,
   'fat': 1.5,
   'sugar': 8.0,
   'carbohydrates': 9.0,
   'protein': 9.0}},
 {'name': 'Grape',
  'id': 81,
  'family': 'Vitaceae',
  'order': 'Vitales',
  'genus': 'Vitis',
  'nutritions': {'calories': 69,
   'fat': 0.16,
   'sugar': 16.0,
   'carbohydrates': 18.1,
   'protein': 0.72}},
 {'name': 'Morus',
  'id': 82,
  'family': 'Moraceae',
  'order': 'Rosales',
  'genus': 'Morus',
  'nutritions': {'calories': 43,
   'fat': 0.39,
   'sugar': 8.1,
   'carbohydrates': 9.8,
   'protein': 1.44}},
 {'name': 'Feijoa',
  'id': 76,
  'family': 'Myrtaceae',
  'order': 'Myrtoideae',
  'genus': 'Sellowiana',
  'nutritions': {'calories': 44,
   'fat': 0.4,
   'sugar': 3.0,
   'carbohydrates': 8.0,
   'protein': 0.6}},
 {'name': 'Avocado',
  'id': 84,
  'family': 'Lauraceae',
  'order': 'Laurales',
  'genus': 'Persea',
  'nutritions': {'calories': 160,
   'fat': 14.66,
   'sugar': 0.66,
   'carbohydrates': 8.53,
   'protein': 2.0}},
 {'name': 'Kiwifruit',
  'id': 85,
  'family': 'Actinidiaceae',
  'order': 'Ericales',
  'genus': 'Actinidia',
  'nutritions': {'calories': 61,
   'fat': 0.5,
   'sugar': 8.9,
   'carbohydrates': 14.6,
   'protein': 1.14}},
 {'name': 'Cranberry',
  'id': 87,
  'family': 'Ericaceae',
  'order': 'Ericales',
  'genus': 'Vaccinium',
  'nutritions': {'calories': 46,
   'fat': 0.1,
   'sugar': 4.0,
   'carbohydrates': 12.2,
   'protein': 0.4}},
 {'name': 'Cherry',
  'id': 9,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 50,
   'fat': 0.3,
   'sugar': 8.0,
   'carbohydrates': 12.0,
   'protein': 1.0}},
 {'name': 'Peach',
  'id': 86,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 39,
   'fat': 0.25,
   'sugar': 8.4,
   'carbohydrates': 9.5,
   'protein': 0.9}},
 {'name': 'Jackfruit',
  'id': 94,
  'family': 'Moraceae',
  'order': 'Rosales',
  'genus': 'Artocarpus',
  'nutritions': {'calories': 95,
   'fat': 0.0,
   'sugar': 19.1,
   'carbohydrates': 23.2,
   'protein': 1.72}},
 {'name': 'Horned Melon',
  'id': 95,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'genus': 'Cucumis',
  'nutritions': {'calories': 44,
   'fat': 1.26,
   'sugar': 0.5,
   'carbohydrates': 7.56,
   'protein': 1.78}},
 {'name': 'Hazelnut',
  'id': 96,
  'family': 'Betulaceae',
  'order': 'Fagales',
  'genus': 'Corylus',
  'nutritions': {'calories': 628,
   'fat': 61.0,
   'sugar': 4.3,
   'carbohydrates': 17.0,
   'protein': 15.0}},
 {'name': 'Pomelo',
  'id': 98,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 37,
   'fat': 0.0,
   'sugar': 8.5,
   'carbohydrates': 9.67,
   'protein': 0.82}},
 {'name': 'Mangosteen',
  'id': 99,
  'family': 'Clusiaceae',
  'order': 'Malpighiales',
  'genus': 'Garcinia',
  'nutritions': {'calories': 73,
   'fat': 0.58,
   'sugar': 16.11,
   'carbohydrates': 17.91,
   'protein': 0.41}},
 {'name': 'Pumpkin',
  'id': 100,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'genus': 'Cucurbita',
  'nutritions': {'calories': 25,
   'fat': 0.3,
   'sugar': 3.3,
   'carbohydrates': 4.6,
   'protein': 1.1}},
 {'name': 'Japanese Persimmon',
  'id': 101,
  'family': ' Ebenaceae',
  'order': ' Ericales',
  'genus': 'Diospyros',
  'nutritions': {'calories': 70,
   'fat': 0.2,
   'sugar': 13.0,
   'carbohydrates': 19.0,
   'protein': 0.6}},
 {'name': 'Papaya',
  'id': 42,
  'family': 'Caricaceae',
  'order': 'Brassicales',
  'genus': 'Carica',
  'nutritions': {'calories': 39,
   'fat': 0.3,
   'sugar': 4.4,
   'carbohydrates': 5.8,
   'protein': 0.5}},
 {'name': 'Annona',
  'id': 103,
  'family': 'Annonaceae',
  'order': 'Rosales',
  'genus': 'Annonas',
  'nutritions': {'calories': 92,
   'fat': 0.29,
   'sugar': 3.4,
   'carbohydrates': 19.1,
   'protein': 1.5}},
 {'name': 'Ceylon Gooseberry',
  'id': 104,
  'family': 'Salicaceae',
  'order': 'Malpighiales',
  'genus': 'Dovyalis',
  'nutritions': {'calories': 47,
   'fat': 0.3,
   'sugar': 8.1,
   'carbohydrates': 9.6,
   'protein': 1.2}}]

In [198]:
df= pd.DataFrame(resultado)
df

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."
5,Durian,60,Malvaceae,Malvales,Durio,"{'calories': 147, 'fat': 5.3, 'sugar': 6.75, '..."
6,Blackberry,64,Rosaceae,Rosales,Rubus,"{'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'ca..."
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,"{'calories': 50, 'fat': 0.34, 'sugar': 5.74, '..."
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,"{'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'ca..."
9,Lychee,67,Sapindaceae,Sapindales,Litchi,"{'calories': 66, 'fat': 0.44, 'sugar': 15.0, '..."
10,Pineapple,10,Bromeliaceae,Poales,Ananas,"{'calories': 50, 'fat': 0.12, 'sugar': 9.85, '..."
11,Fig,68,Moraceae,Rosales,Ficus,"{'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'c..."
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,"{'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'ca..."
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,"{'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'c..."
14,Plum,71,Rosaceae,Rosales,Prunus,"{'calories': 46, 'fat': 0.28, 'sugar': 9.92, '..."
15,Orange,2,Rutaceae,Sapindales,Citrus,"{'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'ca..."
16,GreenApple,72,Rosaceae,Rosales,Malus,"{'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'ca..."
17,Raspberry,23,Rosaceae,Rosales,Rubus,"{'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'ca..."
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,"{'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'ca..."
19,Lemon,26,Rutaceae,Sapindales,Citrus,"{'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'ca..."
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,"{'calories': 60, 'fat': 0.38, 'sugar': 13.7, '..."
21,Blueberry,33,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
22,Apple,6,Rosaceae,Rosales,Malus,"{'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'c..."
23,Guava,37,Myrtaceae,Myrtales,Psidium,"{'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'ca..."
24,Apricot,35,Rosaceae,Rosales,Prunus,"{'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'ca..."
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,"{'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'ca..."
26,Tangerine,77,Rutaceae,Sapindales,Citrus,"{'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'ca..."
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,"{'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'ca..."
28,Lime,44,Rutaceae,Sapindales,Citrus,"{'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'ca..."
29,Pomegranate,79,Lythraceae,Myrtales,Punica,"{'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'c..."
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,"{'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'ca..."
31,Grape,81,Vitaceae,Vitales,Vitis,"{'calories': 69, 'fat': 0.16, 'sugar': 16.0, '..."
32,Morus,82,Moraceae,Rosales,Morus,"{'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'c..."
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,"{'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'ca..."
34,Avocado,84,Lauraceae,Laurales,Persea,"{'calories': 160, 'fat': 14.66, 'sugar': 0.66,..."
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,"{'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'ca..."
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,"{'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'ca..."
37,Cherry,9,Rosaceae,Rosales,Prunus,"{'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'ca..."
38,Peach,86,Rosaceae,Rosales,Prunus,"{'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'c..."
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,"{'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'c..."
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,"{'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'c..."
41,Hazelnut,96,Betulaceae,Fagales,Corylus,"{'calories': 628, 'fat': 61.0, 'sugar': 4.3, '..."
42,Pomelo,98,Rutaceae,Sapindales,Citrus,"{'calories': 37, 'fat': 0.0, 'sugar': 8.5, 'ca..."
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,"{'calories': 73, 'fat': 0.58, 'sugar': 16.11, ..."
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,"{'calories': 25, 'fat': 0.3, 'sugar': 3.3, 'ca..."
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,"{'calories': 70, 'fat': 0.2, 'sugar': 13.0, 'c..."
46,Papaya,42,Caricaceae,Brassicales,Carica,"{'calories': 39, 'fat': 0.3, 'sugar': 4.4, 'ca..."
47,Annona,103,Annonaceae,Rosales,Annonas,"{'calories': 92, 'fat': 0.29, 'sugar': 3.4, 'c..."
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,"{'calories': 47, 'fat': 0.3, 'sugar': 8.1, 'ca..."

In [199]:
nutritions_df = pd.json_normalize(df['nutritions'])
df = pd.concat([df.drop('nutritions', axis=1), nutritions_df], axis=1)
df

,name,id,family,order,genus,calories,fat,sugar,carbohydrates,protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
26,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
28,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
29,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
31,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
32,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
34,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
38,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78
41,Hazelnut,96,Betulaceae,Fagales,Corylus,628,61.00,4.30,17.00,15.00
42,Pomelo,98,Rutaceae,Sapindales,Citrus,37,0.00,8.50,9.67,0.82
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,73,0.58,16.11,17.91,0.41
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,25,0.30,3.30,4.60,1.10
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,70,0.20,13.00,19.00,0.60
46,Papaya,42,Caricaceae,Brassicales,Carica,39,0.30,4.40,5.80,0.50
47,Annona,103,Annonaceae,Rosales,Annonas,92,0.29,3.40,19.10,1.50
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,47,0.30,8.10,9.60,1.20

In [200]:
df.to_json("frutas.json")

##**4- Paginas web**

In [201]:
datos= pd.read_html("AFI's 100 Years...100 Movies - Wikipedia.html")
datos

[       0                      1
 0   1998             100 Movies
 1   1999              100 Stars
 2   2000             100 Laughs
 3   2001            100 Thrills
 4   2002           100 Passions
 5   2003  100 Heroes & Villains
 6   2004              100 Songs
 7   2005       100 Movie Quotes
 8   2005              25 Scores
 9   2006             100 Cheers
 10  2006            25 Musicals
 11  2007   100 Movies (Updated)
 12  2008        AFI's 10 Top 10
 13   vte                    vte,
                       Film  Release year              Director  \
 0             Citizen Kane          1941          Orson Welles
 1               Casablanca          1942        Michael Curtiz
 2            The Godfather          1972  Francis Ford Coppola
 3       Gone with the Wind          1939        Victor Fleming
 4       Lawrence of Arabia          1962            David Lean
 ..                     ...           ...                   ...
 118        Sophie's Choice          1982        Alan J. Pakula
 119  The Last Picture Show          1971     Peter Bogdanovich
 120     Do the Right Thing          1989             Spike Lee
 121           Blade Runner          1982          Ridley Scott
 122              Toy Story          1995         John Lasseter

                               Production companies 1998 Rank 2007 Rank
 0                               RKO Radio Pictures         1         1
 1                            Warner Bros. Pictures         2         3
 2           Paramount Pictures, Alfran Productions         3         2
 3                  Selznick International Pictures         4         6
 4                                 Horizon Pictures         5         7
 ..                                             ...       ...       ...
 118                              ITC Entertainment         -        91
 119                                BBS Productions         -        95
 120                  40 Acres and a Mule Filmworks         -        96
 121                The Ladd Company, Shaw Brothers         -        97
 122  Walt Disney Pictures, Pixar Animation Studios         -        99

 [123 rows x 6 columns]]

In [202]:
len(datos)

2

In [203]:
df= datos[1]
df

,Film,Release year,Director,Production companies,1998 Rank,2007 Rank
0,Citizen Kane,1941,Orson Welles,RKO Radio Pictures,1,1
1,Casablanca,1942,Michael Curtiz,Warner Bros. Pictures,2,3
2,The Godfather,1972,Francis Ford Coppola,"Paramount Pictures, Alfran Productions",3,2
3,Gone with the Wind,1939,Victor Fleming,Selznick International Pictures,4,6
4,Lawrence of Arabia,1962,David Lean,Horizon Pictures,5,7
...,...,...,...,...,...,...
118,Sophie's Choice,1982,Alan J. Pakula,ITC Entertainment,-,91
119,The Last Picture Show,1971,Peter Bogdanovich,BBS Productions,-,95
120,Do the Right Thing,1989,Spike Lee,40 Acres and a Mule Filmworks,-,96
121,Blade Runner,1982,Ridley Scott,"The Ladd Company, Shaw Brothers",-,97
122,Toy Story,1995,John Lasseter,"Walt Disney Pictures, Pixar Animation Studios",-,99

In [204]:
df.to_html("Top_Peliculas.html", index=False)

##**5- Bancos de datos**

In [205]:
import sqlalchemy

In [206]:
from sqlalchemy import create_engine, MetaData, Table, inspect, text

In [207]:
engine= create_engine("sqlite:///:memory:")

In [208]:
df= pd.read_csv("clientes_banco.csv")
df

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438459,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438460,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438461,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438462,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [209]:
df.to_sql("clientes", engine, index=False)

438463

In [210]:
inspector= inspect(engine)

In [211]:
print(inspector.get_table_names())

['clientes']

In [212]:
query= "SELECT * FROM clientes WHERE Categoria_de_renta = 'Empleado'"

In [213]:
empleados=pd.read_sql(query, engine)
empleados

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226055,6837906,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226056,6839936,34,Nivel intermedio,Casado,3,Empleado,Construcción Civil,5,135000.0,1,Casa/Departamento propio
226057,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
226058,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [214]:
empleados= pd.read_sql(sql=text(query), con = engine.connect())
empleados

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226055,6837906,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226056,6839936,34,Nivel intermedio,Casado,3,Empleado,Construcción Civil,5,135000.0,1,Casa/Departamento propio
226057,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
226058,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [215]:
empleados.to_sql("empleados", con = engine.connect(), index=False)

226059

In [216]:
pd.read_sql_table("empleados", con = engine.connect(), columns=["ID_Cliente","Grado_estudio","Rendimiento_anual"])

        ID_Cliente     Grado_estudio  Rendimiento_anual
0          5008804    Nivel superior           427500.0
1          5008805    Nivel superior           427500.0
2          5008806  Nivel intermedio           112500.0
3          5008815    Nivel superior           270000.0
4          5112956    Nivel superior           270000.0
...            ...               ...                ...
226054     6837905  Nivel intermedio           355050.0
226055     6837906  Nivel intermedio           355050.0
226056     6839936  Nivel intermedio           135000.0
226057     6840222  Nivel intermedio           103500.0
226058     6842885  Nivel intermedio           121500.0

[226059 rows x 3 columns]

In [217]:
query= "SELECT * FROM clientes"

In [218]:
pd.read_sql(sql=text(query), con = engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438459,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438460,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438461,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438462,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [219]:
from sqlalchemy.exc import SQLAlchemyError

In [220]:
query= "DELETE FROM clientes WHERE ID_Cliente = '5008804'"
try:
  r_set= engine.connect().execute(text(query))
except SQLAlchemyError as e:
    print(e)
else:
    print("#Registros Borrados:", r_set.rowcount)

#Registros Borrados: 1

In [221]:
query= "SELECT * FROM clientes"
pd.read_sql(sql=text(query), con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
2,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
3,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008810,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438458,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438459,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438460,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438461,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [222]:
query= "UPDATE clientes SET Grado_estudio='Nivel superior' WHERE ID_Cliente = '5008808'"
try:
  r_set= engine.connect().execute(text(query))
except SQLAlchemyError as e:
    print(e)
else:
    print("#Registros actualizados:", r_set.rowcount)

#Registros actualizados: 1

In [223]:
query= "SELECT * FROM clientes"
pd.read_sql(sql=text(query), con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
2,5008808,52,Nivel superior,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
3,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008810,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438458,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438459,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438460,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438461,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [226]:
inspector= inspect(engine)
print(inspector.get_table_names())

['clientes', 'empleados']